title: "Display"
description: |
  This will be the main navigation

patterns:
  display-home:
    title: "Main page photo display"
    description: |
      This is the main page photo display.This will show four pictures of art that will link to subsequent pages.
  display-2:
    title: "Secondary display with titles"
    description: |
      This display will be used for the extras pages because there are subtitles and subsequent description for the work.
  display-3:
    title: "Third display with one title"
    description: |
      This display will be used for the beginning of a section with several other paragraphs attached to the photos with no subheadings.
  display-4:
    title: "Fourth display with No title"
    description: |
      This display will be used for the description of the photo, no heading here as it is a simple description and follows a heading display.
  display-5:
    title: "Fifh display with No title, photo on right"
    description: |
        This display will be used for the description of the photo, but on the opposite side. No heading here as it is a simple description and follows a heading display.
