title: "Display"
description: |
  This will be the main navigation

patterns:
  display-home:
    title: "Main page photo display"
    description: |
      This is the main page photo display.This will show four pictures of art that will link to subsequent pages.
  display-2:
    title: "Secondary display with titles"
    description: |
      This display will be used for the extras pages because there are subtitles and subsequent description for the work.
    fields:
        - name: heading
          type: string
          example: "Research & Background"
        - name: text
          type: string
          example: "StoryBee is a local Apiary that produces raw honey products and encourages education about bees and their vital relationship to the environment. The beekeeper, Kristine, is passionate about mental health and how bees relate to holistic health for marginalized populations."
  display-5:
    title: "Fifh display with No title, photo on right"
    description: |
        This display will be used for the description of the photo, but on the opposite side. No heading here as it is a simple description and follows a heading display.
