title: "Navigation"
description: |
  This will be the main navigation

patterns:
  nav:
    title: "Main Navigation"
    description: |
      This is the navigation on top of the main home page. This is also the base for all remaining pages, included in secondary navigation.
    fields:
      - name: banner_title
        example: "MiriamP."
      - name: banner_class
        example: beet
      - name: banner_title
        example: "Branding"
      - name: banner_class
        example: artichoke
